document.getElementById('iniciar-chat').addEventListener('click', iniciarChat);
document.getElementById('botao-enviar').addEventListener('click', enviarMensagem);
document.getElementById('minimize-button').addEventListener('click', enviarMensagem);
document.getElementById('close-button').addEventListener('click', altenarJanelaChat);

/* Declara uma variável para armazenar o nome do usuário. Inicialmente é uma string vazia. */
let nomeUsuario = '';

/* Define um array que contém pares de perguntas e respostas.*/
const qa = [
    /* Cada objeto contém uma 'pergunta' e uma 'resposta' que corresponde ao chatbot.*/
    { pergunta: "olá", resposta: "Olá! Como posso ajudar você hoje?"},
    { pergunta: "oi", resposta: "Oi! Como posso ajudar você hoje"},
    { pergunta: "qual é o seu nome?", resposta: "Eu sou o Chatbot de Atendimento"},
    { pergunta: "como posso acessar a minha conta?", resposta: "Oferecemos Cursos de HTML, CSS, Javascript e React."},
    { pergunta: "quanto custa o curso de HTML?", resposta: "O curso de HTML custa R$ 100,00."},
    { pergunta: "quanto custa o curso de CSS?", resposta: "O curso de CSS custa R$ 120,00." },
    { pergunta: "quanto custa o curso de JavaScript?", resposta: "O curso de JavaScript custa R$ 150,00." },
    { pergunta: "como faço para me inscrever no curso de HTML?", resposta: "Para se inscrever no curso de HTML, acesse a página do curso e clique em 'Inscrever-se'."},
    { pergunta: "como faço para me inscrever no curso de CSS?", resposta: "Para se inscrever no curso de CSS, acesse a página do curso e clique em 'Inscrever-se'." },
    { pergunta: "como faço para me inscrever no curso de JavaScript?", resposta: "Para se inscrever no curso de JavaScript, acesse a página do curso e clique em 'Inscrever-se'." },
    { pergunta: "qual é a duração do curso de HTML?", resposta: "O curso de HTML tem duração de 4 semanas." },
    { pergunta: "qual é a duração do curso de CSS?", resposta: "O curso de CSS tem duração de 6 semanas." },
    { pergunta: "qual é a duração do curso de JavaScript?", resposta: "O curso de JavaScript tem duração de 8 semanas." },
    { pergunta: "os cursos possuem certificado?", resposta: "Sim, todos os cursos oferecem certificado de conclusão." },
    { pergunta: "como recebo o certificado?", resposta: "O certificado é enviado por e-mail após a conclusão do curso." },
    { pergunta: "quais são as formas de pagamento?", resposta: "Aceitamos pagamentos via cartão de crédito, boleto bancário e PayPal." },
    { pergunta: "posso pagar parcelado?", resposta: "Sim, é possível parcelar o pagamento em até 12 vezes no cartão de crédito." },
    { pergunta: "qual é a carga horária do curso de HTML?", resposta: "O curso de HTML tem uma carga horária de 40 horas." },
    { pergunta: "qual é a carga horária do curso de CSS?", resposta: "O curso de CSS tem uma carga horária de 60 horas." },
    { pergunta: "qual é a carga horária do curso de JavaScript?", resposta: "O curso de JavaScript tem uma carga horária de 80 horas." },
    { pergunta: "os cursos são online?", resposta: "Sim, todos os nossos cursos são 100% online." },
    { pergunta: "como funcionam as aulas?", resposta: "As aulas são em formato de vídeo e você pode assistir no seu próprio ritmo." },
    { pergunta: "posso baixar os materiais?", resposta: "Sim, você pode baixar os materiais complementares dos cursos." },
    { pergunta: "qual é a metodologia de ensino?", resposta: "Nossa metodologia é prática, com muitos exercícios e projetos reais." },
    { pergunta: "há suporte para dúvidas?", resposta: "Sim, você pode tirar suas dúvidas com nossos instrutores via fórum." },
    { pergunta: "qual é o público-alvo dos cursos?", resposta: "Nossos cursos são voltados para iniciantes e desenvolvedores que desejam se atualizar." },
    { pergunta: "preciso de conhecimento prévio?", resposta: "Não, nossos cursos são feitos para quem não tem conhecimento prévio." },
    { pergunta: "qual é o diferencial dos seus cursos?", resposta: "Nosso diferencial é a abordagem prática e a qualidade dos instrutores." },
    { pergunta: "há algum desconto disponível?", resposta: "Sim, oferecemos descontos para pagamentos à vista e promoções sazonais." },
    { pergunta: "como posso acompanhar meu progresso?", resposta: "Você pode acompanhar seu progresso na plataforma, em seu perfil." },
    { pergunta: "há certificado de participação?", resposta: "Sim, ao completar o curso você recebe um certificado de participação." },
    { pergunta: "como acesso os cursos?", resposta: "Você pode acessar os cursos através do nosso site, na área do aluno." },
    { pergunta: "há prazo para concluir o curso?", resposta: "Não, você pode concluir o curso no seu próprio ritmo, sem prazos." },
    { pergunta: "qual é a média salarial de um desenvolvedor web?", resposta: "A média salarial varia, mas um desenvolvedor web júnior pode ganhar entre R$ 3.000,00 e R$ 5.000,00." },
    { pergunta: "os cursos são atualizados?", resposta: "Sim, nossos cursos são constantemente atualizados com as novas tecnologias." },
    { pergunta: "como posso cancelar minha inscrição?", resposta: "Você pode cancelar sua inscrição entrando em contato com nosso suporte." },
    { pergunta: "posso obter reembolso?", resposta: "Sim, oferecemos reembolso total se você cancelar dentro de 7 dias após a compra." },
    { pergunta: "há alguma garantia de aprendizado?", resposta: "Sim, garantimos que você vai aprender se seguir todas as aulas e exercícios." },
    { pergunta: "qual é a diferença entre HTML e CSS?", resposta: "HTML é usado para estruturar o conteúdo da web, enquanto CSS é usado para estilizar a aparência do conteúdo." },
    { pergunta: "o que é JavaScript?", resposta: "JavaScript é uma linguagem de programação usada para criar interatividade em sites." },
    { pergunta: "quais são os pré-requisitos para aprender JavaScript?", resposta: "Não há pré-requisitos, mas é recomendável ter conhecimento básico de HTML e CSS." },
    { pergunta: "posso usar os cursos em mais de um dispositivo?", resposta: "Sim, você pode acessar os cursos em qualquer dispositivo com internet." },
    { pergunta: "os cursos têm exercícios práticos?", resposta: "Sim, todos os nossos cursos incluem muitos exercícios práticos." },
    { pergunta: "há suporte técnico?", resposta: "Sim, oferecemos suporte técnico para ajudar com qualquer problema na plataforma." },
    { pergunta: "posso acessar os cursos a qualquer hora?", resposta: "Sim, nossos cursos estão disponíveis 24 horas por dia, 7 dias por semana." },
    { pergunta: "os cursos têm prazo de validade?", resposta: "Não, uma vez comprado, você tem acesso vitalício ao curso." },
    { pergunta: "posso compartilhar meu acesso?", resposta: "Não, o acesso é individual e intransferível." },
    { pergunta: "há aulas ao vivo?", resposta: "Não, todas as aulas são gravadas para que você possa assistir no seu próprio ritmo." },
    { pergunta: "qual é o conteúdo do curso de HTML?", resposta: "O curso de HTML abrange desde o básico até tópicos mais avançados, incluindo semântica e acessibilidade." },
    { pergunta: "qual é o conteúdo do curso de CSS?", resposta: "O curso de CSS inclui desde conceitos básicos até técnicas avançadas, como Flexbox e Grid Layout." },
    { pergunta: "qual é o conteúdo do curso de JavaScript?", resposta: "O curso de JavaScript cobre desde a sintaxe básica até conceitos avançados, como ES6, DOM e AJAX." },
    { pergunta: "há algum material extra?", resposta: "Sim, todos os cursos incluem materiais extras, como ebooks e links úteis." },
    { pergunta: "posso falar com os instrutores?", resposta: "Sim, você pode enviar mensagens aos instrutores através da plataforma." },
    { pergunta: "os cursos têm avaliação?", resposta: "Sim, ao final de cada módulo você encontra avaliações para testar seus conhecimentos." },
    { pergunta: "há algum pré-requisito para os cursos?", resposta: "Não, qualquer pessoa pode se inscrever em nossos cursos." },
    { pergunta: "quais são os benefícios de aprender HTML, CSS e JavaScript?", resposta: "Aprender essas tecnologias permite criar sites e aplicações web interativas, além de abrir portas para carreiras em desenvolvimento web." },
    { pergunta: "quanto tempo devo dedicar aos cursos?", resposta: "Recomendamos dedicar pelo menos 1 hora por dia para um bom aproveitamento." },
]